# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_historicalcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfiguration',
            name='course_limit',
            field=models.PositiveIntegerField(default=250, help_text=b'Number of courses to show on dashboard'),
        ),
    ]
